name: ansible setup
on:
 workflow_dispatch:
jobs:
 ansible-setup:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v3
    - name: Run ansible-lint
      uses: ansible/ansible-lint-action@main
    - name: print present directory
      run: pwd
      shell: bash
  
