name: get github context
on:
 issues:
  type: [opened]
 workflow_dispatch:
jobs:
 github-context:
  runs-on: ubuntu-latest
  steps:
   - name: get github event
     run: echo '${{ toJSON(github.event) }}'| jq
     shell: bash
 
