name: Ansible Playbook1
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Ansible
      run: sudo apt-get install ansible
    - name: Run Ansible playbook on Localhost
      run: |
       ansible --version
       ansible-playbook msg.yaml
      env:
        ANSIBLE_HOST_KEY_CHECKING: False
    - name: Run Ansible Playbook on provided host
      run: |
       eval `ssh-agent -s`
       pwd
       find / -name id_rsa 

 
       
      
